### ISSUE TITLE
Add support for live properties

### ISSUE THREAD

**Issue by sritchie** [ChristopherChudzicki/mathbox-react#200]
@ChristopherChudzicki , I'm porting the examples and realized that there is a second way to call each constructor that we haven't covered. I'm curious what you think is an appropriate API. On the API docs: https://github.com/unconed/mathbox/blob/master/docs/api.md

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/69635/207965400-b4dd3132-7b5d-4f7b-9225-67f4d94227fa.png">

I can do this now with a `ref`.

What do you think of accepting this as a `:bind` property? I guess we need to wire it in here: https://github.com/ChristopherChudzicki/mathbox-react/blob/main/src/components/components.tsx#L62-L68

**Comment by sritchie** [comment]
Here's a demo in Clojurescript where the `matrix` property of `transform4` depends on the projection angle that's being set by the UI...

![2022-12-15 14 46 30](https://user-images.githubusercontent.com/69635/207974356-c11c4a52-6486-49da-8d17-9486bf6d70a5.gif)

**Comment by ChristopherChudzicki** [comment]
Interesting. I hadn't realized that `set()` had a second arg, or really the purpose of `bind()` until now. Neat.

Do you know what the `live` boolean properties are for? (9 primitives have it, according to https://github.com/unconed/mathbox/blob/master/docs/primitives.md).

I'm not sure what API `mathbox-react` should expose for this. Some options I can think of:
1. Infer from value: `<Line color={staticValue} width={liveFunction} />` width would be live, but color would not. *I don't think this would work very well, particularly because some property values are allowed to be functions themselves.*
2. prefixes ... `<Line color={staticValue} liveWidth={liveFunction} />`
3. a single object ... `<Line color={staticValue} liveProperties={{ width: liveFunction, other: otherLiveFunc }}/>`. Annoying, since inline objects cause extra re-renders, but can work around that with standard react techniques.
4. an array of live property names `<Line color={staticValue} width={liveFunction} liveProps={["width"]} />` ... Same annoying as (3), but probably also annoying aspects.
5. No support. Use `ref` if you want this.

All in all, I think I would lean toward (3): easy type definitions, simple API.

@sritchie What do you think? Thanks for pointing this out, btw!

**Comment by sritchie** [comment]
I think 3 is the way to go; as you say it's nice and clean, and it's simple to mechanically port code over from the non-React examples to this style.

Good stuff!

I am really liking https://github.com/pmndrs/leva, by the way. Not that you have a need for floating controls but it's been solid.

**Comment by sritchie** [comment]
I actually do know what `live` is for. That is a property on components with an `expr` in every case, I believe, and toggles whether or not the `expr` is called a single time (for each point in an area, say) to populate the `Area`, or continuously.

Here's an example of an animation that uses `live` to generate those (physics-simulation) arrows in the phase portrait:

![2022-11-29 15 50 03](https://user-images.githubusercontent.com/69635/207984921-d4b65843-cd1a-4e10-9370-9204de5c5953.gif)

**Comment by sritchie** [comment]
I also just realized that bind is only used in this exponential demo to query the state - and your react code handles all of that for us more efficiently!

For cases where the variable updates based on the incoming time or delta variables, this new feature will be excellent.

**Comment by ChristopherChudzicki** [comment]
@sritchie Ah, thanks for that reminder about `live`. I do recall that now... I guess I had forgotten about it because it defaults to true, I think. I believe `liveProps` are now working now (in mathbox-react)!

**Comment by sritchie** [comment]
Excellent I'll give it a try. I reminded myself about it because I was doing a physics simulation with some interpreted code that was super slow, and salvaged it by turning off live...

**Comment by ChristopherChudzicki** [comment]
Or rather, now it should be... initially forgot to publish. Now published!
