### ISSUE TITLE
error on remount if stats plugin is registered

### ISSUE THREAD

**Issue by sritchie** [ChristopherChudzicki/mathbox-react#202]
Hey, I don't have a repro for you here yet... but on any component with that "stats" plugin registered, like this component: https://github.com/mentat-collective/mathbox.cljs/blob/1cfdc4891157a728f1974921b0867f718afed84b/dev/mathbox/examples/math/helitorus.cljc#L126

I am getting this error on a re-mount:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ctor.uninstall (http://localhost:8766/js/cljs-runtime/module$node_modules$threestrap$src$extra$stats.js:3:60)
    at Bootstrap.__uninstall (http://localhost:8766/js/cljs-runtime/module$node_modules$threestrap$src$bootstrap.js:8:276)
    at http://localhost:8766/js/cljs-runtime/module$node_modules$threestrap$src$bootstrap.js:7:253
    at Array.forEach (<anonymous>)
    at Bootstrap.uninstall (http://localhost:8766/js/cljs-runtime/module$node_modules$threestrap$src$bootstrap.js:7:237)
    at Bootstrap.destroy (http://localhost:8766/js/cljs-runtime/module$node_modules$threestrap$src$bootstrap.js:5:264)
    at http://localhost:8766/js/cljs-runtime/module$node_modules$mathbox_react$build$cjs$index.js:33:366
    at safelyCallDestroy (http://localhost:8766/js/cljs-runtime/module$node_modules$react_dom$cjs$react_dom_development.js:488:496)
    at commitHookEffectListUnmount (http://localhost:8766/js/cljs-runtime/module$node_modules$react_dom$cjs$react_dom_development.js:497:424)
    at flushPassiveEffects (http://localhost:8766/js/cljs-runtime/module$node_modules$react_dom$cjs$react_dom_development.js:617:152)
(anonymous) @ react-dom.development.js:22901
callCallback @ react-dom.development.js:4122
invokeGuardedCallbackImpl @ react-dom.development.js:4224
invokeGuardedCallback @ react-dom.development.js:4475
reportUncaughtErrorInDEV @ react-dom.development.js:22898
captureCommitPhaseError @ react-dom.development.js:27152
safelyCallDestroy @ react-dom.development.js:8229
commitHookEffectListUnmount @ react-dom.development.js:23124
flushPassiveEffects @ react-dom.development.js:25084
commitRootImpl @ react-dom.development.js:26978
commitRoot @ react-dom.development.js:26706
performSyncWorkOnRoot @ react-dom.development.js:26146
flushSyncCallbacks @ react-dom.development.js:12113
(anonymous) @ react-dom.development.js:25684
```

Maybe it's just a Clojurescript thing, but on React 18 pressing the option key seems to remount all components??

**Comment by sritchie** [comment]
This is with the latest rc!

**Comment by ChristopherChudzicki** [comment]
Glad it's not just the newest version... BTW: I expect to be using mathbox-react a lot more in the coming weeks/months. I haven't used in hardly at all until now, but am now starting to add graphics to math3d-next.

**Comment by sritchie** [comment]
This is the issue, of course: https://github.com/unconed/threestrap/blob/master/src/extra/stats.js#L19

I'm too tired now to think through why it's already been removed!

**Comment by ChristopherChudzicki** [comment]
I think this is actually a bug in Threestrap, not a bug in mathbox-react. You'll get the same error if:

1. Clone https://github.com/unconed/threestrap
2. Open `examples/element_cube`
3. In console, call `three.destroy()

I think mathbox-react exacerbates this issue by making it easier to instantiate threestrap (via mathbox) inside a non-body element.

IMO, the fix is to switch Threestrap from calling [`Node.removeChild(child)`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) on the parent to calling [`Element.remove()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/remove) on the child itself.

`removeChild` seems like a strictly worse API to me, since it requires a reference to both the parent and the child. My best guess as to why Threestrap is using it is that it seems like `remove` was introduced in later versions of JS. E.g., ie supports removeChild but not remove... cf
- https://caniuse.com/?search=remove
- https://caniuse.com/mdn-api_node_removechild

I'll make a PR to threestrap in the next day or two.

**Comment by ChristopherChudzicki** [comment]
@sritchie I appear not to have collaborator status on Threestrap, so I can't actually request your reviews, but PRs are up to address this. I didn't realize the tests over there were broken... I'll look into that next.

https://github.com/unconed/threestrap/pulls

Probably after the holidays I will email Steven and ask for collaborator status.

**Comment by sritchie** [comment]
I'll make a note to ask Steven!

**Comment by sritchie** [comment]
Closing since we've covered this in threestrap.
