### ISSUE TITLE
Import error when using in NextJS

### ISSUE THREAD

**Issue by Abhimanyu-Jha** [ChristopherChudzicki/mathbox-react#206]
```
SyntaxError: Cannot use import statement outside a module at node_modules/mathbox/src/index.js (10)
```

Hey, trying to run setup this library for use. I've yarn added 
1. "mathbox-react": "^0.0.11-rc",
2. "mathbox": "2.0.0",
3. "three": "^0.148.0",

The page seems to open to this error in the mathbox module. Are there any fixes/ workarounds for this?

**Comment by ChristopherChudzicki** [comment]
Are you using any sort of bundler? (Webpack, vite,...). I would not expect  ES Modules (import / export syntax) to work well without a bundler.[^1].

I would recommend using [vite](https://vitejs.dev/guide/).. 

[^1]: It is possible to use ESM in `<script>` tags with `module` attribute, but it doesn't generally work well (yet) because  ESM [doesn't support bare name imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#importing_modules_as_bare_names).

**Comment by Abhimanyu-Jha** [comment]
Hey,
Yes i am actually using Next JS and I believe it uses webpack 5 as the
default

**Comment by ChristopherChudzicki** [comment]
Do you have a repository you can share?  I’ve never used NextJS but I’m happy to try and look into it. (Might take me a few days to find the time)

**Comment by Abhimanyu-Jha** [comment]
Yeah, I've shared the private repository with you. You can find the relevant code under ./pages/mideo-3.js.
Thanks!

**Comment by ChristopherChudzicki** [comment]
@Abhimanyu-Jha Everything seemed to work fine for me after `yarn install` and `yarn dev`:

<img width="1098" alt="Screenshot 2022-12-30 at 4 22 35 PM" src="https://user-images.githubusercontent.com/9010790/210112667-0c0d4d2b-7ef1-44f4-9f5b-7c8c8b83ab84.png">

**Comment by Abhimanyu-Jha** [comment]
Yeah, but after you refresh the page, or make any changes in the file and save the file, it it shows the error and there's no way to remove it.

**Comment by ChristopherChudzicki** [comment]
> Yeah, but after you refresh the page, or make any changes in the file and save the file, it it shows the error and there's no way to remove it.

My experience was that:
- loading localhost:3000 and navigating to localhost:3000/mideo-3 always works correctly, even after reloading and saving; this includes hot-reloads where the page automatically reloads when you change source content
- localhost:3000/mideo-3 directly (or refreshing on that page) did not work

As mentioned, I am not a next-js expert, but comments like [this](https://github.com/asyncapi/asyncapi-react/issues/177#issuecomment-729823940) make me wonder if this is related to SSR in NextJS. My understanding is that when loading  localhost:3000/mideo-3, NextJS tries to render that page on the server before serving it to you. It seems reasonable to me that mathbox wouldn't work great with SSR since it relies on a bunch of browser APIs.

**Comment by Abhimanyu-Jha** [comment]
Thanks for the help, this works as expected in vite 👌🏻
