### ISSUE TITLE
How to refer to elements across cartesians?

### ISSUE THREAD

**Issue by Abhimanyu-Jha** [ChristopherChudzicki/mathbox-react#228]
Hey, I was wondering how could we refer to a Mathbox element which is across a cartesian. Pls see the example below.
```
<ContainedMathbox
			options={{
				plugins: ["core", "controls", "cursor"],
				controls: { klass: OrbitControls },
			}}
			containerStyle={{
				height: "100vh",
				width: "100vw",
			}}
		>
			<Cartesian
				range={[
					[-3, 3],
					[-3, 3],
					[-3, 3],
				]}
				scale={[2, 2, 2]}
			>
				<GridAndAxes />
				<Surface
					points="shpereData"
					shaded
					lineX={false}
					lineY={false}
					color={"#ffe000"}
					fill
				/>
				<Cartesian
					range={[
						[0, 2 * Math.PI], // u
						[-Math.PI / 2, Math.PI / 2], // v
					]}
				>
					<Area
						id="shpereData"
						width={64}
						height={64}
						channels={3}
						ref={sphereRef}
						expr={(emit, u, v, i, j, t) => {
							const x = radius * Math.cos(u) * Math.cos(v);
							const y = radius * Math.sin(u) * Math.cos(v);
							const z = radius * Math.sin(v);
							emit(x, z, y);
						}}
					/>
				</Cartesian>
			</Cartesian>
		</ContainedMathbox>
```
		
Here I get the error that surface is unable to find #sphereData. Help will be appreciated!

**Comment by ChristopherChudzicki** [comment]
**First:** I honestly forget if nesting cartesians is valid in mathbox. It may well be. It looks to me like you want to specify a plot range on the Area/Surface. The way that I would do that is using `rangeX` and `rangeY`:

```jsx
const SimpleExample: React.FC = () => (
	<ContainedMathbox
		options={{
			plugins: ["core", "controls", "cursor"],
			controls: { klass: OrbitControls },
		}}
		containerStyle={{ height: "100vh" }}
	>
		<Cartesian>
			<Axis axis="x" color="orange" />
			<Axis axis="y" color="blue" />
			<Axis axis="z" color="green" />
			<Grid axes="xz" />
		</Cartesian>
		<Area
			id="sphere-data"
			width={64}
			height={64}
			rangeX={[0, 2 * Math.PI]}
			rangeY={[-Math.PI / 2, Math.PI / 2]}
			channels={3}
			expr={(emit, u, v, i, j, t) => {
				const x = radius * Math.cos(u) * Math.cos(v);
				const y = radius * Math.sin(u) * Math.cos(v);
				const z = radius * Math.sin(v);
				emit(x, z, y);
			}}
		/>
		<Surface
			points="#sphere-data"
			shaded
			lineX={false}
			lineY={false}
			color="#ffe000"
			fill
		/>
	</ContainedMathbox>
)
```

### Your issue
Regarding how to reference "sphereData"... What you did should have worked. It seems like Mathbox does not like camelcase ids (very strange). I've opened https://github.com/unconed/mathbox/issues/54 in the mathbox repo. I will try to look into that at some point this week.

In the meantime, I would recommend one of three options:
1. Use kebab-case, like in my example above
2. If you place the Surface immediately after the Area, you won't need to specify "points". This is because the default for "points" is "<", which means "use the previous node". This works well for simple stuff.
3. You can also pass references to Mathbox nodes themselves. I.e., if you have a reference to the `Area` node, you can pass it to `Surface.points`: `<Surface points={AreaNode} />`. This is a little tricky in React because in order to get a reference to the area node you'd need to do something like `<Area ref={setAreaNode} />`.

In simple cases, I'd recommend (2), although it doesn't work if you need multiple Surfaces referencing the same Area.

**Comment by Abhimanyu-Jha** [comment]
Oh, I didn't know setting the ranges as attributes was possible. This works for me. Thanks a lot!

**Comment by ChristopherChudzicki** [comment]
PS: Regarding `rangeX` and `rangeY` on area... if you're using Typescript, Typescript will tell you that they don't exist. They do. The TS definitions will be updated in the next release of Mathbox. (Which should be in the next few days). The typedefs for rangeX, etc, were added in https://github.com/unconed/mathbox/pull/50

**Comment by ChristopherChudzicki** [comment]
@Abhimanyu-Jha I should add a link to it in this readme, but these docs https://github.com/unconed/mathbox/tree/master/docs can be useful. (They are a bit terse, but helps discovering what's available.)

**Comment by ChristopherChudzicki** [comment]
@Abhimanyu-Jha Also... note that you forgot the '#' in your initial attempt. The `points` property is a CSS selector, so it needs a '#' for ids.

**Comment by Abhimanyu-Jha** [comment]
Yeah, I usually see the available attributes by ctrl+spacebar - ing the element. (since no definitions were there, i missed it). Re: next mathbox release... thats awesome!
